spring:
  profiles:
    active: local
  application:
    name: spring-boot-oauth2
  output:
    ansi:
      enabled: always

management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: "*"
  #        include: ["health","info","loggers","httptrace","env","beans","caches","configprops","mappings","scheduledtasks","sessions","threaddump","jolokia", "logfile", "refresh"]

  endpoint:
    health:
      show-details: ALWAYS

---

spring:
  profiles: local
  datasource:
    platform: h2
#    url: jdbc:h2:~/oauth2;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:mem:oauth;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: embedded
#    script 에서 한글 입력 가능 하게
    sql-script-encoding: UTF-8
#    SQL 오류 발생하면 안종료 - true, 종료 - false
    continue-on-error: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: true
      hibernate.use_sql_comments: true
      hibernate.jdbc.lob.non_contextual_creation: true
    hibernate:
      # ddl-auto 설정
      # none: 기본 값이며 아무 일도 일어나지 않는다.
      # create: 데이터베이스를 drop 한 후, 데이터베이스를 새로 생성한다.
      # create-drop: SessionFactory가 시작될 때 스키마를 drop하고 재생성하며, SessionFactory가 종료될 때도 스키마를 drop 한다.
      # validate: 데이터베이스 스키마를 검증 한다.
      # update: 데이터베이스 스키마를 갱신 한다.
      ddl-auto: create
    show-sql: true
    open-in-view: true
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2

management:
  endpoints:
    web:
      cors:
        allowed-origins:
          - http://www.halfclub.com
          - http://www.boribori.co.kr
          - http://www.ogage.co.kr
          - http://www.trcc.tk
          - http://cloud-eureka1-local-service-pig.trcc.com:8761
          - http://cloud-eureka2-local-service-pig.trcc.com:8761
          - http://cloud-config-local-service-pig.trcc.com:8888
          - http://cloud-monitor-local-service-pig.trcc.com:8080
          - http://cloud-oauth-local-service-pig.trcc.com:8081
          - http://cloud-gateway-local-service-pig.trcc.com:8080
          - http://api-skeleton-local-service-pig.trcc.com:28001
          - http://api-skeleton-local-service-pig.trcc.com:28002
          - http://api-skeleton-local-service-pig.trcc.com:28003
          - http://api-skeleton-local-service-pig.trcc.com:28004
          - http://api-skeleton-local-service-pig.trcc.com:28005
          - http://client-skeleton-local-service-pig.trcc.com:38001
          - http://mhalf-main-local-service-pig.trcc.com:38101
          - http://half-list-local-service-pig.trcc.com:38102
          - http://half-main-local-service-pig.trcc.com:38201
          - http://half-list-local-service-pig.trcc.com:38202
          - http://mbori-main-local-service-pig.trcc.com:38301
          - http://mbori-list-local-service-pig.trcc.com:38302
          - http://bori-main-local-service-pig.trcc.com:38401
          - http://bori-list-local-service-pig.trcc.com:38402
          - https://client-payment-local-service-pig.trcc.com:38443
          - http://cloud-eureka1-local-service-pig.trcc.tk:8761
          - http://cloud-eureka2-local-service-pig.trcc.tk:8761
          - http://cloud-config-local-service-pig.trcc.tk:8888
          - http://cloud-monitor-local-service-pig.trcc.tk:8080
          - http://cloud-oauth-local-service-pig.trcc.tk:8081
          - http://cloud-gateway-local-service-pig.trcc.tk:8080
          - http://api-skeleton-local-service-pig.trcc.tk:28001
          - http://api-skeleton-local-service-pig.trcc.tk:28002
          - http://api-skeleton-local-service-pig.trcc.tk:28003
          - http://api-skeleton-local-service-pig.trcc.tk:28004
          - http://api-skeleton-local-service-pig.trcc.tk:28005
          - http://client-skeleton-local-service-pig.trcc.tk:38001
          - http://mhalf-main-local-service-pig.trcc.tk:38101
          - http://half-list-local-service-pig.trcc.tk:38102
          - http://half-main-local-service-pig.trcc.tk:38201
          - http://half-list-local-service-pig.trcc.tk:38202
          - http://mbori-main-local-service-pig.trcc.tk:38301
          - http://mbori-list-local-service-pig.trcc.tk:38302
          - http://bori-main-local-service-pig.trcc.tk:38401
          - http://bori-list-local-service-pig.trcc.tk:38402
          - https://client-payment-local-service-pig.trcc.tk:38443
#        allowed-headers:
#          - Access-Control-Allow-Origin
        allowed-methods:
          - GET
          - POST
          - PUT
          - OPTION
          - DELETE
        allow-credentials: true

security:
  oauth2:
    authorization:
      jwt:
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2IjjRXQxM4u8kPMHoLYy
          Q5+hrtzI86WxUkpoghpUNcp/3J6spLddBo74bgMjRm7HZjPWj5PUdvhGwDympE4N
          zWRDhtfrDoCnxsAzLMSES3zql5VisJXSPGz2jmatVTsXL1icJq/muLJCw5u7Nez3
          8kIGQQ+xbrUfmyL+5MnQrplfWG8xkX5E+zTUIoQgSh/50QWTajJ1QQaXeKQFRSEF
          yt2DdU/BVMO4AflRpXvWnSY1AS+gTa/8RKktvANCeT/FunxXqMl84AYVeJGotdXc
          vbV7iP/fE7LbfrO7UFXtLFh+uKX7OE3RCoPoAR5R6glfktQ4WnCBuvb6cP4ddCDJ
          mwIDAQAB
          -----END PUBLIC KEY-----





logging:
  level:
    ROOT: warn
    com.zzizily: debug
#    org.springframework.boot: info
#    org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener.debug: debug
#    org.springframework.boot.devtools: debug
#    org.springframework.web: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
    org.springframework.security: debug