-- hibernate only SQL Script
-- INSERT INTO oauth_user(username, password, site_id, use_yn) VALUES ('user', '{noop}password', 1, 'Y');
-- INSERT INTO oauth_user(username, password, site_id, use_yn) VALUES ('admin', '{noop}password', 1, 'Y');
-- INSERT INTO oauth_user_role (role) VALUES ('ROLE_USER');
-- INSERT INTO oauth_user_role (role) VALUES ('ROLE_ADMIN');
